apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digitalocean-cloud-controller-manager
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: digitalocean-cloud-controller-manager
