apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: operating-system-manager
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: operating-system-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: operating-system-manager-webhook
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: operating-system-manager-webhook
