apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.cluster.k8s.io
  annotations:
    "api-approved.kubernetes.io": "unapproved, legacy API"
spec:
  group: cluster.k8s.io
  scope: Namespaced
  names:
    kind: Cluster
    plural: clusters
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
      subresources:
        # status enables the status subresource.
        status: {}
