apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machines.cluster.k8s.io
  annotations:
    "api-approved.kubernetes.io": "unapproved, legacy API"
spec:
  group: cluster.k8s.io
  scope: Namespaced
  names:
    kind: Machine
    plural: machines
    singular: machine
    listKind: MachineList
    shortNames: ["ma"]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
      additionalPrinterColumns:
        - name: Provider
          type: string
          jsonPath: .spec.providerSpec.value.cloudProvider
        - name: OS
          type: string
          jsonPath: .spec.providerSpec.value.operatingSystem
        - name: Node
          type: string
          jsonPath: .status.nodeRef.name
        - name: Kubelet
          type: string
          jsonPath: .spec.versions.kubelet
        - name: Address
          type: string
          jsonPath: .status.addresses[0].address
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Deleted
          type: date
          jsonPath: .metadata.deletionTimestamp
          priority: 1
