apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-controller-webhook
  namespace: kube-system

{{ if .OperatingSystemManagerEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machine-controller-webhook
  namespace: kube-system
rules:
  - apiGroups:
      - operatingsystemmanager.k8c.io
    resources:
      - operatingsystemprofiles
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-controller-webhook
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machine-controller-webhook
subjects:
  - kind: ServiceAccount
    name: machine-controller-webhook
    namespace: kube-system
{{ end}}
