namespace: kubermatic
name: kubeone
version: "0.10.0-alpha.0"
readme: README.md
license:
    - "Apache-2.0"
repository: https://github.com/kubermatic/kubeone
documentation: https://github.com/kubermatic/kubeone/tree/release/v0.10.0-alpha.0/docs
homepage: https://github.com/kubermatic/kubeone
issues: https://github.com/kubermatic/kubeone/issues
