apiVersion: v1
kind: Secret
metadata:
  name: nutanix-webhook-certs
  namespace: kube-system
data:
  "tls.crt": |
{{ .Certificates.NutanixCSIWebhookCert | b64enc | indent 4 }}
  "tls.key": |
{{ .Certificates.NutanixCSIWebhookKey | b64enc | indent 4 }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validation-webhook.snapshot.storage.k8s.io"
  namespace: kube-system
webhooks:
- name: "validation-webhook.snapshot.storage.k8s.io"
  rules:
  - apiGroups:   ["snapshot.storage.k8s.io"]
    apiVersions: ["v1", "v1beta1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["volumesnapshots", "volumesnapshotcontents"]
    scope:       "*"
  clientConfig:
    service:
      namespace: kube-system
      name: "snapshot-validation-service"
      path: "/volumesnapshot"
    caBundle: |
{{ .Certificates.KubernetesCA | b64enc | indent 6 }}
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  timeoutSeconds: 2
