run:
  issues-exit-code: 1
  build-tags:
  - e2e
  skip-dirs:
  - hack
  - vendor
  - pkg/apis/kubeadm

  skip-files:
  - zz_generated.*.go

linters:
  disable-all: true
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - contextcheck
  - deadcode
  - dogsled
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - forcetypeassert
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - makezero
  - misspell
  - nakedret
  - nilnil
  - nlreturn
  - noctx
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - structcheck
  - stylecheck
  - tenv
  - thelper
  - tparallel
  - unconvert
  - unparam
  - unused
  - varcheck
  - wastedassign
  - whitespace

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: k8c.io/kubeone
  importas:
    no-unaliased: true
    alias:
    - pkg: k8c.io/kubeone/pkg/apis/kubeone
      alias: kubeoneapi
    - pkg: k8c.io/kubeone/pkg/apis/(\w+)/(v[\w\d]+)
      alias: $1$2
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
      alias: $1$2

issues:
  exclude-rules:
  - path: pkg/apis/kubeone
    text: "func SetDefaults_"

  - path: pkg/apis/kubeone
    text: "func Convert_"

  - path: pkg/apis/kubeone
    text: "type name will be used as kubeone.KubeOneCluster by other packages"

  - path: test/e2e
    text: "cyclomatic complexity 35 of func `TestClusterConformance` is high"

  - path: pkg/scripts
    text: "`registry` always receives `\"127.0.0.1:5000\"`"

  - path: pkg/credentials
    text: "cyclomatic complexity 34 of func `openstackValidationFunc` is high"

  - path: pkg/addons
    text: "cyclomatic complexity 34 of func `newAddonsApplier` is high"
