run:
  issues-exit-code: 1
  build-tags:
  - e2e

linters:
  disable-all: true
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - copyloopvar
  - dogsled
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - forcetypeassert
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - intrange
  - makezero
  - misspell
  - nakedret
  - nilnil
  - nlreturn
  - noctx
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - stylecheck
  - tenv
  - tparallel
  - unconvert
  - unparam
  - unused
  - wastedassign
  - whitespace

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: k8c.io
  importas:
    no-unaliased: true
    alias:
    - pkg: k8c.io/kubeone/pkg/apis/kubeone
      alias: kubeoneapi
    - pkg: k8c.io/kubeone/pkg/apis/(\w+)/(v[\w\d]+)
      alias: $1$2
    - pkg: k8c.io/machine-controller/pkg/apis/cluster/v1alpha1
      alias: clusterv1alpha1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
      alias: $1$2

issues:
  exclude:
  - "G115: integer overflow conversion (.+)"

  exclude-dirs:
  - hack
  - vendor
  - pkg/apis/kubeadm

  exclude-files:
  - zz_generated.*.go

  exclude-rules:
  - path: pkg/apis/kubeone
    text: "func SetDefaults_"

  - path: pkg/apis/kubeone
    text: "func Convert_"

  - path: pkg/apis/kubeone
    text: "type name will be used as kubeone.KubeOneCluster by other packages"

  - path: test/e2e
    text: "cyclomatic complexity 35 of func `TestClusterConformance` is high"

  - path: pkg/scripts
    text: "`registry` always receives `\"127.0.0.1:5000\"`"

  - path: pkg/credentials
    text: "cyclomatic complexity 36 of func `openstackValidationFunc` is high"

  - path: pkg/apis/kubeone
    text: "cyclomatic complexity 35 of func `ValidateCloudProviderSpec` is high"

  - path: pkg/templates/kubeadm/v1beta3
    text: "cyclomatic complexity 33 of func `NewConfig` is high"
