run:
  issues-exit-code: 1
  build-tags:
  - e2e
  skip-dirs:
  - hack
  - vendor
  - pkg/apis/kubeadm

  skip-files:
  - zz_generated.*.go

linters:
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - errcheck
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - misspell
  - nakedret
  - staticcheck
  - structcheck
  - stylecheck
  - unconvert
  - unused
  - varcheck

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/kubermatic/kubeone

issues:
  exclude:
  - "`defaultRetryBackoff` - `retries` always receives `3`"
  - "func SetDefaults_APIEndpoints should be SetDefaultsAPIEndpoints"
  - "func SetDefaults_ClusterNetwork should be SetDefaultsClusterNetwork"
  - "func SetDefaults_Features should be SetDefaultsFeatures"
  - "func SetDefaults_Hosts should be SetDefaultsHosts"
  - "func SetDefaults_KubeOneCluster should be SetDefaultsKubeOneCluster"
  - "func SetDefaults_MachineController should be SetDefaultsMachineController"
  - "func SetDefaults_SystemPackages should be SetDefaultsSystemPackages"
