run:
  issues-exit-code: 1
  build-tags:
  - e2e
  skip-dirs:
  - hack
  - vendor
  - pkg/apis/kubeadm

  skip-files:
  - zz_generated.*.go

linters:
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - errcheck
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - golint
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - scopelint
  - staticcheck
  - structcheck
  - stylecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: k8c.io/kubeone

issues:
  exclude-rules:
  - path: pkg/apis/kubeone
    text: "func SetDefaults_"

  - path: pkg/apis/kubeone
    text: "func Convert_"

  - path: pkg/apis/kubeone
    text: "type name will be used as kubeone.KubeOneCluster by other packages"

  - path: test/e2e
    text: "cyclomatic complexity 35 of func `TestClusterConformance` is high"

  - path: pkg/scripts
    text: "`registry` always receives `\"127.0.0.1:5000\"`"
