run:
  issues-exit-code: 1

linters:
  enable-all: true
  disable:
  - interfacer
  - dupl
  - maligned
  - megacheck
  - lll
  - prealloc
  - gochecknoinits
  - gochecknoglobals

linters-settings:
  govet:
    check-shadowing: true
