run:
  issues-exit-code: 1
  skip-dirs:
  - hack
  - vendor

linters:
  enable-all: true
  disable:
  - funlen
  - interfacer
  - dupl
  - maligned
  - megacheck
  - lll
  - prealloc
  - gochecknoinits
  - gochecknoglobals

linters-settings:
  govet:
    check-shadowing: true

issues:
  exclude:
    - "type name will be used as kubeone.KubeOneCluster by other packages, and that stutters; consider calling this Cluster"
    - "don't use underscores in Go names; func SetDefaults_KubeOneCluster should be SetDefaultsKubeOneCluster"
    - "don't use underscores in Go names; func SetDefaults_Hosts should be SetDefaultsHosts"
    - "don't use underscores in Go names; func SetDefaults_APIEndpoints should be SetDefaultsAPIEndpoints"
    - "don't use underscores in Go names; func SetDefaults_ClusterNetwork should be SetDefaultsClusterNetwork"
    - "don't use underscores in Go names; func SetDefaults_Features should be SetDefaultsFeatures"
    - "don't use underscores in Go names; func SetDefaults_MachineController should be SetDefaultsMachineController"
    - "don't use underscores in Go names; func SetDefaults_SystemPackages should be SetDefaultsSystemPackages"
    - "G101: Potential hardcoded credentials"
    - "G106: Use of ssh InsecureIgnoreHostKey should be audited"
    - "`defaultRetryBackoff` - `retries` always receives `3`"
