{{ $version := semver .Config.Versions.Kubernetes }}
{{- if ge $version.Minor 21 }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: csi-azuredisk-controller
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: csi-azuredisk-controller
---
{{- if ge $version.Minor 21 }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: csi-snapshot-controller
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: csi-snapshot-controller
