# Copyright 2019 The KubeOne Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install KubeOne cluster
  hosts: localhost
  connection: local
  roles:
    - kubeone_config
    - kubeone_upgrade
  vars:
    kubeone_name: testcluster  # Give the cluster a name.
    kubeone_versions_kubernetes: 1.15.0  # Kubernetes version to install.
    kubeone_cloudProvider_name: packet  # We use Packet in this example.
    kubeone_apiEndpoint_host: 0.0.0.0  # This is the address used to access the control plane. It's is highly recommended to use a load balancer with control plane nodes as an endpoint.
    kubeone_workers:  # Defining one pool of workers that will execute our workload.
      - name: testcluster-pool  # The name makes them recognizable.
        providerSpec:  # How shall a worker look like?
          cloudProviderSpec:  # Information for packet.
            facilities: [ams1]  # Where shall the worker be placed?
            instanceType: t1.small.x86  # Properties of created instances.
            projectID:XXX  # Your project ID.
          operatingSystem: ubuntu  # The distro used.
          operatingSystemSpec:  # Customizations.
            distUpgradeOnBoot: false  # Don't upgrade system on boot.
          sshPublicKeys:  # Your public key so you may SSH onto your workers.
            - ssh-rsa AAAAxxxx dev@example.com
        replicas: 1  # We want one instance per default.
    kubeone_hosts:  # Nodes we want to have the master on. This needs to exist already. You can create them with terraform.
      - publicAddress: 0.0.0.0  # Outer IP or hostname of a master node.
        privateAddress: 0.0.0.0 # Inner IP or hostname of a master node.
        sshUsername: root  # Username to connect with.
      - publicAddress: 0.0.0.0
        privateAddress: 0.0.0.0
        sshUsername: root
      - publicAddress: 0.0.0.0
        privateAddress: 0.0.0.0
        sshUsername: root
