---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-cloud-controller-manager
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-cloud-controller-manager
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevirt-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: kubevirt-cloud-controller-manager
    namespace: kube-system
---
apiVersion: v1
data:
  infra-kubeconfig: {{ .Config.CloudProvider.KubeVirt.InfraClusterKubeconfig }}
kind: Secret
metadata:
  name: infra-kubeconfig
  namespace: kube-system
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  config: |
    kubeconfig: /etc/kubernetes/kubeconfig/infra-kubeconfig
    namespace: {{ .Config.CloudProvider.KubeVirt.InfraNamespace }}
    instancesV2:
        zoneAndRegionEnabled: {{ .Config.CloudProvider.KubeVirt.ZoneAndRegionEnabled }}
    loadBalancer:
        enabled: {{ .Config.CloudProvider.KubeVirt.CCMLoadBalancerEnabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubevirt-cloud-controller-manager
  name: kubevirt-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-cloud-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubevirt-cloud-controller-manager
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --cloud-config=/etc/cloud/config
            - --cloud-provider=kubevirt
            - --cluster-name
            - {{ .Config.Name }}
          command:
            - /bin/kubevirt-cloud-controller-manager
          image: quay.io/kubevirt/kubevirt-cloud-controller-manager:v0.5.1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          name: cloud-controller-manager
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/kubernetes/kubeconfig
              name: infra-kubeconfig
              readOnly: true
            - mountPath: /etc/cloud
              name: cloud-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: kubevirt-cloud-controller-manager
      volumes:
        - name: infra-kubeconfig
          secret:
            defaultMode: 420
            secretName: infra-kubeconfig
        - name: cloud-config
          configMap:
            name: cloud-config
