apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud-config: |
    kubeconfig: /var/run/secrets/infracluster/KUBEVIRT_KUBECONFIG
    namespace: {{ .Config.CloudProvider.KubeVirt.InfraNamespace }}
    instancesV2:
      zoneAndRegionEnabled: {{ .Config.CloudProvider.KubeVirt.ZoneAndRegionEnabled }}
    loadBalancer:
      enabled: {{ .Config.CloudProvider.KubeVirt.CCMLoadBalancerEnabled }}
