name: "Feature Request"
description: "Request a new Kubermatic KubeOne feature"
labels: ["sig/cluster-management", "kind/bug"]
body:
  - type: textarea
    id: user-story
    attributes:
      label: "Description of the feature you would like to add / User story"
      description: |
        We've provided an example format of the user story below. You're free to use any other format as well.
      value: |
        As a <user persona>
        I would like to <functionality>
        in order to <benefit>
    validations:
      required: true
  
  - type: textarea
    id: details
    attributes:
      label: Solution details
      description: |
        Please, provide a bullet-pointed list or a few sentences of requirements that have to be met to mark the requested feature (user story) complete.
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Alternative approaches
      description: |
        Optional: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  
  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: |
        Optional: Please try to explain some use cases why this feature would be valuable for you. If you can, please also explain what metrics would be improved for you with having this feature.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Optional: Additional information about the feature you're reporting.
    validations:
      required: false
