// Code generated by "stringer -type=Resource"; DO NOT EDIT.

package images

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CalicoCNI-1]
	_ = x[CalicoController-2]
	_ = x[CalicoNode-3]
	_ = x[Flannel-4]
	_ = x[Cilium-5]
	_ = x[CiliumOperator-6]
	_ = x[HubbleRelay-7]
	_ = x[HubbleUI-8]
	_ = x[HubbleUIBackend-9]
	_ = x[HubbleProxy-10]
	_ = x[WeaveNetCNIKube-11]
	_ = x[WeaveNetCNINPC-12]
	_ = x[DNSNodeCache-13]
	_ = x[MachineController-14]
	_ = x[MetricsServer-15]
	_ = x[ClusterAutoscaler-16]
	_ = x[CSIAttacher-17]
	_ = x[CSINodeDriverRegistar-18]
	_ = x[CSIProvisioner-19]
	_ = x[CSISnapshotter-20]
	_ = x[CSIResizer-21]
	_ = x[CSILivenessProbe-22]
	_ = x[AwsCCM-23]
	_ = x[AzureCCM-24]
	_ = x[AzureCNM-25]
	_ = x[AzureFileCSI-26]
	_ = x[AzureFileCSIAttacher-27]
	_ = x[AzureFileCSILivenessProbe-28]
	_ = x[AzureFileCSINodeDriverRegistar-29]
	_ = x[AzureFileCSIProvisioner-30]
	_ = x[AzureFileCSIResizer-31]
	_ = x[AzureFileCSISnapshotter-32]
	_ = x[AzureFileCSISnapshotterController-33]
	_ = x[AzureDiskCSI-34]
	_ = x[AzureDiskCSIAttacher-35]
	_ = x[AzureDiskCSILivenessProbe-36]
	_ = x[AzureDiskCSINodeDriverRegistar-37]
	_ = x[AzureDiskCSIProvisioner-38]
	_ = x[AzureDiskCSIResizer-39]
	_ = x[AzureDiskCSISnapshotter-40]
	_ = x[AzureDiskCSISnapshotterController-41]
	_ = x[DigitaloceanCCM-42]
	_ = x[HetznerCCM-43]
	_ = x[HetznerCSI-44]
	_ = x[OpenstackCCM-45]
	_ = x[OpenstackCSI-46]
	_ = x[PacketCCM-47]
	_ = x[VsphereCCM-48]
	_ = x[VsphereCSIDriver-49]
	_ = x[VsphereCSISyncer-50]
}

const _Resource_name = "CalicoCNICalicoControllerCalicoNodeFlannelCiliumCiliumOperatorHubbleRelayHubbleUIHubbleUIBackendHubbleProxyWeaveNetCNIKubeWeaveNetCNINPCDNSNodeCacheMachineControllerMetricsServerClusterAutoscalerCSIAttacherCSINodeDriverRegistarCSIProvisionerCSISnapshotterCSIResizerCSILivenessProbeAwsCCMAzureCCMAzureCNMAzureFileCSIAzureFileCSIAttacherAzureFileCSILivenessProbeAzureFileCSINodeDriverRegistarAzureFileCSIProvisionerAzureFileCSIResizerAzureFileCSISnapshotterAzureFileCSISnapshotterControllerAzureDiskCSIAzureDiskCSIAttacherAzureDiskCSILivenessProbeAzureDiskCSINodeDriverRegistarAzureDiskCSIProvisionerAzureDiskCSIResizerAzureDiskCSISnapshotterAzureDiskCSISnapshotterControllerDigitaloceanCCMHetznerCCMHetznerCSIOpenstackCCMOpenstackCSIPacketCCMVsphereCCMVsphereCSIDriverVsphereCSISyncer"

var _Resource_index = [...]uint16{0, 9, 25, 35, 42, 48, 62, 73, 81, 96, 107, 122, 136, 148, 165, 178, 195, 206, 227, 241, 255, 265, 281, 287, 295, 303, 315, 335, 360, 390, 413, 432, 455, 488, 500, 520, 545, 575, 598, 617, 640, 673, 688, 698, 708, 720, 732, 741, 751, 767, 783}

func (i Resource) String() string {
	i -= 1
	if i < 0 || i >= Resource(len(_Resource_index)-1) {
		return "Resource(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Resource_name[_Resource_index[i]:_Resource_index[i+1]]
}
