---
apiVersion: v1
kind: Secret
metadata:
  name: vcloud-basic-auth
  namespace: kube-system
data:
  username: "{{ with .Credentials.VCD_USER }}{{ . | b64enc }}{{ end }}"
  password: "{{ with .Credentials.VCD_PASSWORD }}{{ . | b64enc }}{{ end }}"
  refreshToken: "{{ with .Credentials.VCD_API_TOKEN }}{{ . | b64enc }}{{ end }}"
