---
apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: vmware-system-csi
data:
  "csi-migration": "{{ .CSIMigration }}"
  "trigger-csi-fullsync": "false"
  "pv-to-backingdiskobjectid-mapping": "false"
