apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flatcar-linux-update-operator
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: flatcar-linux-update-operator
