// +build !ignore_autogenerated

/*
Copyright The KubeOne Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	unsafe "unsafe"

	kubeone "github.com/kubermatic/kubeone/pkg/apis/kubeone"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*kubeone.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_APIEndpoint_To_kubeone_APIEndpoint(a.(*APIEndpoint), b.(*kubeone.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_APIEndpoint_To_v1alpha1_APIEndpoint(a.(*kubeone.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CNI)(nil), (*kubeone.CNI)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CNI_To_kubeone_CNI(a.(*CNI), b.(*kubeone.CNI), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.CNI)(nil), (*CNI)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_CNI_To_v1alpha1_CNI(a.(*kubeone.CNI), b.(*CNI), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProviderSpec)(nil), (*kubeone.CloudProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProviderSpec_To_kubeone_CloudProviderSpec(a.(*CloudProviderSpec), b.(*kubeone.CloudProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.CloudProviderSpec)(nil), (*CloudProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_CloudProviderSpec_To_v1alpha1_CloudProviderSpec(a.(*kubeone.CloudProviderSpec), b.(*CloudProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterNetworkConfig)(nil), (*kubeone.ClusterNetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterNetworkConfig_To_kubeone_ClusterNetworkConfig(a.(*ClusterNetworkConfig), b.(*kubeone.ClusterNetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.ClusterNetworkConfig)(nil), (*ClusterNetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_ClusterNetworkConfig_To_v1alpha1_ClusterNetworkConfig(a.(*kubeone.ClusterNetworkConfig), b.(*ClusterNetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DNSConfig)(nil), (*kubeone.DNSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DNSConfig_To_kubeone_DNSConfig(a.(*DNSConfig), b.(*kubeone.DNSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.DNSConfig)(nil), (*DNSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_DNSConfig_To_v1alpha1_DNSConfig(a.(*kubeone.DNSConfig), b.(*DNSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DynamicAuditLog)(nil), (*kubeone.DynamicAuditLog)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamicAuditLog_To_kubeone_DynamicAuditLog(a.(*DynamicAuditLog), b.(*kubeone.DynamicAuditLog), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.DynamicAuditLog)(nil), (*DynamicAuditLog)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_DynamicAuditLog_To_v1alpha1_DynamicAuditLog(a.(*kubeone.DynamicAuditLog), b.(*DynamicAuditLog), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Features)(nil), (*kubeone.Features)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Features_To_kubeone_Features(a.(*Features), b.(*kubeone.Features), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.Features)(nil), (*Features)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_Features_To_v1alpha1_Features(a.(*kubeone.Features), b.(*Features), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostConfig)(nil), (*kubeone.HostConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostConfig_To_kubeone_HostConfig(a.(*HostConfig), b.(*kubeone.HostConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.HostConfig)(nil), (*HostConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_HostConfig_To_v1alpha1_HostConfig(a.(*kubeone.HostConfig), b.(*HostConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubeOneCluster)(nil), (*kubeone.KubeOneCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KubeOneCluster_To_kubeone_KubeOneCluster(a.(*KubeOneCluster), b.(*kubeone.KubeOneCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.KubeOneCluster)(nil), (*KubeOneCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_KubeOneCluster_To_v1alpha1_KubeOneCluster(a.(*kubeone.KubeOneCluster), b.(*KubeOneCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineControllerConfig)(nil), (*kubeone.MachineControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineControllerConfig_To_kubeone_MachineControllerConfig(a.(*MachineControllerConfig), b.(*kubeone.MachineControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.MachineControllerConfig)(nil), (*MachineControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_MachineControllerConfig_To_v1alpha1_MachineControllerConfig(a.(*kubeone.MachineControllerConfig), b.(*MachineControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricsServer)(nil), (*kubeone.MetricsServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricsServer_To_kubeone_MetricsServer(a.(*MetricsServer), b.(*kubeone.MetricsServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.MetricsServer)(nil), (*MetricsServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_MetricsServer_To_v1alpha1_MetricsServer(a.(*kubeone.MetricsServer), b.(*MetricsServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkConfig)(nil), (*kubeone.NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkConfig_To_kubeone_NetworkConfig(a.(*NetworkConfig), b.(*kubeone.NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.NetworkConfig)(nil), (*NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_NetworkConfig_To_v1alpha1_NetworkConfig(a.(*kubeone.NetworkConfig), b.(*NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeLocalDNSCache)(nil), (*kubeone.NodeLocalDNSCache)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeLocalDNSCache_To_kubeone_NodeLocalDNSCache(a.(*NodeLocalDNSCache), b.(*kubeone.NodeLocalDNSCache), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.NodeLocalDNSCache)(nil), (*NodeLocalDNSCache)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_NodeLocalDNSCache_To_v1alpha1_NodeLocalDNSCache(a.(*kubeone.NodeLocalDNSCache), b.(*NodeLocalDNSCache), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenIDConnect)(nil), (*kubeone.OpenIDConnect)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OpenIDConnect_To_kubeone_OpenIDConnect(a.(*OpenIDConnect), b.(*kubeone.OpenIDConnect), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.OpenIDConnect)(nil), (*OpenIDConnect)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_OpenIDConnect_To_v1alpha1_OpenIDConnect(a.(*kubeone.OpenIDConnect), b.(*OpenIDConnect), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenIDConnectConfig)(nil), (*kubeone.OpenIDConnectConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OpenIDConnectConfig_To_kubeone_OpenIDConnectConfig(a.(*OpenIDConnectConfig), b.(*kubeone.OpenIDConnectConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.OpenIDConnectConfig)(nil), (*OpenIDConnectConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_OpenIDConnectConfig_To_v1alpha1_OpenIDConnectConfig(a.(*kubeone.OpenIDConnectConfig), b.(*OpenIDConnectConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PodSecurityPolicy)(nil), (*kubeone.PodSecurityPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodSecurityPolicy_To_kubeone_PodSecurityPolicy(a.(*PodSecurityPolicy), b.(*kubeone.PodSecurityPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.PodSecurityPolicy)(nil), (*PodSecurityPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_PodSecurityPolicy_To_v1alpha1_PodSecurityPolicy(a.(*kubeone.PodSecurityPolicy), b.(*PodSecurityPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProviderSpec)(nil), (*kubeone.ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderSpec_To_kubeone_ProviderSpec(a.(*ProviderSpec), b.(*kubeone.ProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.ProviderSpec)(nil), (*ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_ProviderSpec_To_v1alpha1_ProviderSpec(a.(*kubeone.ProviderSpec), b.(*ProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxyConfig)(nil), (*kubeone.ProxyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxyConfig_To_kubeone_ProxyConfig(a.(*ProxyConfig), b.(*kubeone.ProxyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.ProxyConfig)(nil), (*ProxyConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_ProxyConfig_To_v1alpha1_ProxyConfig(a.(*kubeone.ProxyConfig), b.(*ProxyConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VersionConfig)(nil), (*kubeone.VersionConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VersionConfig_To_kubeone_VersionConfig(a.(*VersionConfig), b.(*kubeone.VersionConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.VersionConfig)(nil), (*VersionConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_VersionConfig_To_v1alpha1_VersionConfig(a.(*kubeone.VersionConfig), b.(*VersionConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerConfig)(nil), (*kubeone.WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerConfig_To_kubeone_WorkerConfig(a.(*WorkerConfig), b.(*kubeone.WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubeone.WorkerConfig)(nil), (*WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubeone_WorkerConfig_To_v1alpha1_WorkerConfig(a.(*kubeone.WorkerConfig), b.(*WorkerConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_APIEndpoint_To_kubeone_APIEndpoint(in *APIEndpoint, out *kubeone.APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_APIEndpoint_To_kubeone_APIEndpoint is an autogenerated conversion function.
func Convert_v1alpha1_APIEndpoint_To_kubeone_APIEndpoint(in *APIEndpoint, out *kubeone.APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha1_APIEndpoint_To_kubeone_APIEndpoint(in, out, s)
}

func autoConvert_kubeone_APIEndpoint_To_v1alpha1_APIEndpoint(in *kubeone.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_kubeone_APIEndpoint_To_v1alpha1_APIEndpoint is an autogenerated conversion function.
func Convert_kubeone_APIEndpoint_To_v1alpha1_APIEndpoint(in *kubeone.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_kubeone_APIEndpoint_To_v1alpha1_APIEndpoint(in, out, s)
}

func autoConvert_v1alpha1_CNI_To_kubeone_CNI(in *CNI, out *kubeone.CNI, s conversion.Scope) error {
	out.Provider = kubeone.CNIProvider(in.Provider)
	out.Encrypted = in.Encrypted
	return nil
}

// Convert_v1alpha1_CNI_To_kubeone_CNI is an autogenerated conversion function.
func Convert_v1alpha1_CNI_To_kubeone_CNI(in *CNI, out *kubeone.CNI, s conversion.Scope) error {
	return autoConvert_v1alpha1_CNI_To_kubeone_CNI(in, out, s)
}

func autoConvert_kubeone_CNI_To_v1alpha1_CNI(in *kubeone.CNI, out *CNI, s conversion.Scope) error {
	out.Provider = CNIProvider(in.Provider)
	out.Encrypted = in.Encrypted
	return nil
}

// Convert_kubeone_CNI_To_v1alpha1_CNI is an autogenerated conversion function.
func Convert_kubeone_CNI_To_v1alpha1_CNI(in *kubeone.CNI, out *CNI, s conversion.Scope) error {
	return autoConvert_kubeone_CNI_To_v1alpha1_CNI(in, out, s)
}

func autoConvert_v1alpha1_CloudProviderSpec_To_kubeone_CloudProviderSpec(in *CloudProviderSpec, out *kubeone.CloudProviderSpec, s conversion.Scope) error {
	out.Name = kubeone.CloudProviderName(in.Name)
	out.External = in.External
	out.CloudConfig = in.CloudConfig
	return nil
}

// Convert_v1alpha1_CloudProviderSpec_To_kubeone_CloudProviderSpec is an autogenerated conversion function.
func Convert_v1alpha1_CloudProviderSpec_To_kubeone_CloudProviderSpec(in *CloudProviderSpec, out *kubeone.CloudProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProviderSpec_To_kubeone_CloudProviderSpec(in, out, s)
}

func autoConvert_kubeone_CloudProviderSpec_To_v1alpha1_CloudProviderSpec(in *kubeone.CloudProviderSpec, out *CloudProviderSpec, s conversion.Scope) error {
	out.Name = CloudProviderName(in.Name)
	out.External = in.External
	out.CloudConfig = in.CloudConfig
	return nil
}

// Convert_kubeone_CloudProviderSpec_To_v1alpha1_CloudProviderSpec is an autogenerated conversion function.
func Convert_kubeone_CloudProviderSpec_To_v1alpha1_CloudProviderSpec(in *kubeone.CloudProviderSpec, out *CloudProviderSpec, s conversion.Scope) error {
	return autoConvert_kubeone_CloudProviderSpec_To_v1alpha1_CloudProviderSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterNetworkConfig_To_kubeone_ClusterNetworkConfig(in *ClusterNetworkConfig, out *kubeone.ClusterNetworkConfig, s conversion.Scope) error {
	out.PodSubnet = in.PodSubnet
	out.ServiceSubnet = in.ServiceSubnet
	out.ServiceDomainName = in.ServiceDomainName
	out.NodePortRange = in.NodePortRange
	out.CNI = (*kubeone.CNI)(unsafe.Pointer(in.CNI))
	return nil
}

// Convert_v1alpha1_ClusterNetworkConfig_To_kubeone_ClusterNetworkConfig is an autogenerated conversion function.
func Convert_v1alpha1_ClusterNetworkConfig_To_kubeone_ClusterNetworkConfig(in *ClusterNetworkConfig, out *kubeone.ClusterNetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterNetworkConfig_To_kubeone_ClusterNetworkConfig(in, out, s)
}

func autoConvert_kubeone_ClusterNetworkConfig_To_v1alpha1_ClusterNetworkConfig(in *kubeone.ClusterNetworkConfig, out *ClusterNetworkConfig, s conversion.Scope) error {
	out.PodSubnet = in.PodSubnet
	out.ServiceSubnet = in.ServiceSubnet
	out.ServiceDomainName = in.ServiceDomainName
	out.NodePortRange = in.NodePortRange
	out.CNI = (*CNI)(unsafe.Pointer(in.CNI))
	return nil
}

// Convert_kubeone_ClusterNetworkConfig_To_v1alpha1_ClusterNetworkConfig is an autogenerated conversion function.
func Convert_kubeone_ClusterNetworkConfig_To_v1alpha1_ClusterNetworkConfig(in *kubeone.ClusterNetworkConfig, out *ClusterNetworkConfig, s conversion.Scope) error {
	return autoConvert_kubeone_ClusterNetworkConfig_To_v1alpha1_ClusterNetworkConfig(in, out, s)
}

func autoConvert_v1alpha1_DNSConfig_To_kubeone_DNSConfig(in *DNSConfig, out *kubeone.DNSConfig, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	return nil
}

// Convert_v1alpha1_DNSConfig_To_kubeone_DNSConfig is an autogenerated conversion function.
func Convert_v1alpha1_DNSConfig_To_kubeone_DNSConfig(in *DNSConfig, out *kubeone.DNSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DNSConfig_To_kubeone_DNSConfig(in, out, s)
}

func autoConvert_kubeone_DNSConfig_To_v1alpha1_DNSConfig(in *kubeone.DNSConfig, out *DNSConfig, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	return nil
}

// Convert_kubeone_DNSConfig_To_v1alpha1_DNSConfig is an autogenerated conversion function.
func Convert_kubeone_DNSConfig_To_v1alpha1_DNSConfig(in *kubeone.DNSConfig, out *DNSConfig, s conversion.Scope) error {
	return autoConvert_kubeone_DNSConfig_To_v1alpha1_DNSConfig(in, out, s)
}

func autoConvert_v1alpha1_DynamicAuditLog_To_kubeone_DynamicAuditLog(in *DynamicAuditLog, out *kubeone.DynamicAuditLog, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_v1alpha1_DynamicAuditLog_To_kubeone_DynamicAuditLog is an autogenerated conversion function.
func Convert_v1alpha1_DynamicAuditLog_To_kubeone_DynamicAuditLog(in *DynamicAuditLog, out *kubeone.DynamicAuditLog, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamicAuditLog_To_kubeone_DynamicAuditLog(in, out, s)
}

func autoConvert_kubeone_DynamicAuditLog_To_v1alpha1_DynamicAuditLog(in *kubeone.DynamicAuditLog, out *DynamicAuditLog, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_kubeone_DynamicAuditLog_To_v1alpha1_DynamicAuditLog is an autogenerated conversion function.
func Convert_kubeone_DynamicAuditLog_To_v1alpha1_DynamicAuditLog(in *kubeone.DynamicAuditLog, out *DynamicAuditLog, s conversion.Scope) error {
	return autoConvert_kubeone_DynamicAuditLog_To_v1alpha1_DynamicAuditLog(in, out, s)
}

func autoConvert_v1alpha1_Features_To_kubeone_Features(in *Features, out *kubeone.Features, s conversion.Scope) error {
	out.PodSecurityPolicy = (*kubeone.PodSecurityPolicy)(unsafe.Pointer(in.PodSecurityPolicy))
	out.NodeLocalDNSCache = (*kubeone.NodeLocalDNSCache)(unsafe.Pointer(in.NodeLocalDNSCache))
	out.DynamicAuditLog = (*kubeone.DynamicAuditLog)(unsafe.Pointer(in.DynamicAuditLog))
	out.MetricsServer = (*kubeone.MetricsServer)(unsafe.Pointer(in.MetricsServer))
	out.OpenIDConnect = (*kubeone.OpenIDConnect)(unsafe.Pointer(in.OpenIDConnect))
	return nil
}

// Convert_v1alpha1_Features_To_kubeone_Features is an autogenerated conversion function.
func Convert_v1alpha1_Features_To_kubeone_Features(in *Features, out *kubeone.Features, s conversion.Scope) error {
	return autoConvert_v1alpha1_Features_To_kubeone_Features(in, out, s)
}

func autoConvert_kubeone_Features_To_v1alpha1_Features(in *kubeone.Features, out *Features, s conversion.Scope) error {
	out.PodSecurityPolicy = (*PodSecurityPolicy)(unsafe.Pointer(in.PodSecurityPolicy))
	out.NodeLocalDNSCache = (*NodeLocalDNSCache)(unsafe.Pointer(in.NodeLocalDNSCache))
	out.DynamicAuditLog = (*DynamicAuditLog)(unsafe.Pointer(in.DynamicAuditLog))
	out.MetricsServer = (*MetricsServer)(unsafe.Pointer(in.MetricsServer))
	out.OpenIDConnect = (*OpenIDConnect)(unsafe.Pointer(in.OpenIDConnect))
	return nil
}

// Convert_kubeone_Features_To_v1alpha1_Features is an autogenerated conversion function.
func Convert_kubeone_Features_To_v1alpha1_Features(in *kubeone.Features, out *Features, s conversion.Scope) error {
	return autoConvert_kubeone_Features_To_v1alpha1_Features(in, out, s)
}

func autoConvert_v1alpha1_HostConfig_To_kubeone_HostConfig(in *HostConfig, out *kubeone.HostConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.PublicAddress = in.PublicAddress
	out.PrivateAddress = in.PrivateAddress
	out.SSHPort = in.SSHPort
	out.SSHUsername = in.SSHUsername
	out.SSHPrivateKeyFile = in.SSHPrivateKeyFile
	out.SSHAgentSocket = in.SSHAgentSocket
	out.Hostname = in.Hostname
	out.OperatingSystem = in.OperatingSystem
	out.IsLeader = in.IsLeader
	return nil
}

// Convert_v1alpha1_HostConfig_To_kubeone_HostConfig is an autogenerated conversion function.
func Convert_v1alpha1_HostConfig_To_kubeone_HostConfig(in *HostConfig, out *kubeone.HostConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostConfig_To_kubeone_HostConfig(in, out, s)
}

func autoConvert_kubeone_HostConfig_To_v1alpha1_HostConfig(in *kubeone.HostConfig, out *HostConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.PublicAddress = in.PublicAddress
	out.PrivateAddress = in.PrivateAddress
	out.SSHPort = in.SSHPort
	out.SSHUsername = in.SSHUsername
	out.SSHPrivateKeyFile = in.SSHPrivateKeyFile
	out.SSHAgentSocket = in.SSHAgentSocket
	out.Hostname = in.Hostname
	out.OperatingSystem = in.OperatingSystem
	out.IsLeader = in.IsLeader
	return nil
}

// Convert_kubeone_HostConfig_To_v1alpha1_HostConfig is an autogenerated conversion function.
func Convert_kubeone_HostConfig_To_v1alpha1_HostConfig(in *kubeone.HostConfig, out *HostConfig, s conversion.Scope) error {
	return autoConvert_kubeone_HostConfig_To_v1alpha1_HostConfig(in, out, s)
}

func autoConvert_v1alpha1_KubeOneCluster_To_kubeone_KubeOneCluster(in *KubeOneCluster, out *kubeone.KubeOneCluster, s conversion.Scope) error {
	out.Name = in.Name
	out.Hosts = *(*[]kubeone.HostConfig)(unsafe.Pointer(&in.Hosts))
	if err := Convert_v1alpha1_APIEndpoint_To_kubeone_APIEndpoint(&in.APIEndpoint, &out.APIEndpoint, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CloudProviderSpec_To_kubeone_CloudProviderSpec(&in.CloudProvider, &out.CloudProvider, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_VersionConfig_To_kubeone_VersionConfig(&in.Versions, &out.Versions, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterNetworkConfig_To_kubeone_ClusterNetworkConfig(&in.ClusterNetwork, &out.ClusterNetwork, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxyConfig_To_kubeone_ProxyConfig(&in.Proxy, &out.Proxy, s); err != nil {
		return err
	}
	out.Workers = *(*[]kubeone.WorkerConfig)(unsafe.Pointer(&in.Workers))
	out.MachineController = (*kubeone.MachineControllerConfig)(unsafe.Pointer(in.MachineController))
	if err := Convert_v1alpha1_Features_To_kubeone_Features(&in.Features, &out.Features, s); err != nil {
		return err
	}
	out.Credentials = *(*map[string]string)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_v1alpha1_KubeOneCluster_To_kubeone_KubeOneCluster is an autogenerated conversion function.
func Convert_v1alpha1_KubeOneCluster_To_kubeone_KubeOneCluster(in *KubeOneCluster, out *kubeone.KubeOneCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeOneCluster_To_kubeone_KubeOneCluster(in, out, s)
}

func autoConvert_kubeone_KubeOneCluster_To_v1alpha1_KubeOneCluster(in *kubeone.KubeOneCluster, out *KubeOneCluster, s conversion.Scope) error {
	out.Name = in.Name
	out.Hosts = *(*[]HostConfig)(unsafe.Pointer(&in.Hosts))
	if err := Convert_kubeone_APIEndpoint_To_v1alpha1_APIEndpoint(&in.APIEndpoint, &out.APIEndpoint, s); err != nil {
		return err
	}
	if err := Convert_kubeone_CloudProviderSpec_To_v1alpha1_CloudProviderSpec(&in.CloudProvider, &out.CloudProvider, s); err != nil {
		return err
	}
	if err := Convert_kubeone_VersionConfig_To_v1alpha1_VersionConfig(&in.Versions, &out.Versions, s); err != nil {
		return err
	}
	if err := Convert_kubeone_ClusterNetworkConfig_To_v1alpha1_ClusterNetworkConfig(&in.ClusterNetwork, &out.ClusterNetwork, s); err != nil {
		return err
	}
	if err := Convert_kubeone_ProxyConfig_To_v1alpha1_ProxyConfig(&in.Proxy, &out.Proxy, s); err != nil {
		return err
	}
	out.Workers = *(*[]WorkerConfig)(unsafe.Pointer(&in.Workers))
	out.MachineController = (*MachineControllerConfig)(unsafe.Pointer(in.MachineController))
	if err := Convert_kubeone_Features_To_v1alpha1_Features(&in.Features, &out.Features, s); err != nil {
		return err
	}
	out.Credentials = *(*map[string]string)(unsafe.Pointer(&in.Credentials))
	return nil
}

// Convert_kubeone_KubeOneCluster_To_v1alpha1_KubeOneCluster is an autogenerated conversion function.
func Convert_kubeone_KubeOneCluster_To_v1alpha1_KubeOneCluster(in *kubeone.KubeOneCluster, out *KubeOneCluster, s conversion.Scope) error {
	return autoConvert_kubeone_KubeOneCluster_To_v1alpha1_KubeOneCluster(in, out, s)
}

func autoConvert_v1alpha1_MachineControllerConfig_To_kubeone_MachineControllerConfig(in *MachineControllerConfig, out *kubeone.MachineControllerConfig, s conversion.Scope) error {
	out.Deploy = in.Deploy
	out.Provider = kubeone.CloudProviderName(in.Provider)
	return nil
}

// Convert_v1alpha1_MachineControllerConfig_To_kubeone_MachineControllerConfig is an autogenerated conversion function.
func Convert_v1alpha1_MachineControllerConfig_To_kubeone_MachineControllerConfig(in *MachineControllerConfig, out *kubeone.MachineControllerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineControllerConfig_To_kubeone_MachineControllerConfig(in, out, s)
}

func autoConvert_kubeone_MachineControllerConfig_To_v1alpha1_MachineControllerConfig(in *kubeone.MachineControllerConfig, out *MachineControllerConfig, s conversion.Scope) error {
	out.Deploy = in.Deploy
	out.Provider = CloudProviderName(in.Provider)
	return nil
}

// Convert_kubeone_MachineControllerConfig_To_v1alpha1_MachineControllerConfig is an autogenerated conversion function.
func Convert_kubeone_MachineControllerConfig_To_v1alpha1_MachineControllerConfig(in *kubeone.MachineControllerConfig, out *MachineControllerConfig, s conversion.Scope) error {
	return autoConvert_kubeone_MachineControllerConfig_To_v1alpha1_MachineControllerConfig(in, out, s)
}

func autoConvert_v1alpha1_MetricsServer_To_kubeone_MetricsServer(in *MetricsServer, out *kubeone.MetricsServer, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_v1alpha1_MetricsServer_To_kubeone_MetricsServer is an autogenerated conversion function.
func Convert_v1alpha1_MetricsServer_To_kubeone_MetricsServer(in *MetricsServer, out *kubeone.MetricsServer, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricsServer_To_kubeone_MetricsServer(in, out, s)
}

func autoConvert_kubeone_MetricsServer_To_v1alpha1_MetricsServer(in *kubeone.MetricsServer, out *MetricsServer, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_kubeone_MetricsServer_To_v1alpha1_MetricsServer is an autogenerated conversion function.
func Convert_kubeone_MetricsServer_To_v1alpha1_MetricsServer(in *kubeone.MetricsServer, out *MetricsServer, s conversion.Scope) error {
	return autoConvert_kubeone_MetricsServer_To_v1alpha1_MetricsServer(in, out, s)
}

func autoConvert_v1alpha1_NetworkConfig_To_kubeone_NetworkConfig(in *NetworkConfig, out *kubeone.NetworkConfig, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.Gateway = in.Gateway
	if err := Convert_v1alpha1_DNSConfig_To_kubeone_DNSConfig(&in.DNS, &out.DNS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NetworkConfig_To_kubeone_NetworkConfig is an autogenerated conversion function.
func Convert_v1alpha1_NetworkConfig_To_kubeone_NetworkConfig(in *NetworkConfig, out *kubeone.NetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkConfig_To_kubeone_NetworkConfig(in, out, s)
}

func autoConvert_kubeone_NetworkConfig_To_v1alpha1_NetworkConfig(in *kubeone.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.Gateway = in.Gateway
	if err := Convert_kubeone_DNSConfig_To_v1alpha1_DNSConfig(&in.DNS, &out.DNS, s); err != nil {
		return err
	}
	return nil
}

// Convert_kubeone_NetworkConfig_To_v1alpha1_NetworkConfig is an autogenerated conversion function.
func Convert_kubeone_NetworkConfig_To_v1alpha1_NetworkConfig(in *kubeone.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	return autoConvert_kubeone_NetworkConfig_To_v1alpha1_NetworkConfig(in, out, s)
}

func autoConvert_v1alpha1_NodeLocalDNSCache_To_kubeone_NodeLocalDNSCache(in *NodeLocalDNSCache, out *kubeone.NodeLocalDNSCache, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_v1alpha1_NodeLocalDNSCache_To_kubeone_NodeLocalDNSCache is an autogenerated conversion function.
func Convert_v1alpha1_NodeLocalDNSCache_To_kubeone_NodeLocalDNSCache(in *NodeLocalDNSCache, out *kubeone.NodeLocalDNSCache, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeLocalDNSCache_To_kubeone_NodeLocalDNSCache(in, out, s)
}

func autoConvert_kubeone_NodeLocalDNSCache_To_v1alpha1_NodeLocalDNSCache(in *kubeone.NodeLocalDNSCache, out *NodeLocalDNSCache, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_kubeone_NodeLocalDNSCache_To_v1alpha1_NodeLocalDNSCache is an autogenerated conversion function.
func Convert_kubeone_NodeLocalDNSCache_To_v1alpha1_NodeLocalDNSCache(in *kubeone.NodeLocalDNSCache, out *NodeLocalDNSCache, s conversion.Scope) error {
	return autoConvert_kubeone_NodeLocalDNSCache_To_v1alpha1_NodeLocalDNSCache(in, out, s)
}

func autoConvert_v1alpha1_OpenIDConnect_To_kubeone_OpenIDConnect(in *OpenIDConnect, out *kubeone.OpenIDConnect, s conversion.Scope) error {
	out.Enable = in.Enable
	if err := Convert_v1alpha1_OpenIDConnectConfig_To_kubeone_OpenIDConnectConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_OpenIDConnect_To_kubeone_OpenIDConnect is an autogenerated conversion function.
func Convert_v1alpha1_OpenIDConnect_To_kubeone_OpenIDConnect(in *OpenIDConnect, out *kubeone.OpenIDConnect, s conversion.Scope) error {
	return autoConvert_v1alpha1_OpenIDConnect_To_kubeone_OpenIDConnect(in, out, s)
}

func autoConvert_kubeone_OpenIDConnect_To_v1alpha1_OpenIDConnect(in *kubeone.OpenIDConnect, out *OpenIDConnect, s conversion.Scope) error {
	out.Enable = in.Enable
	if err := Convert_kubeone_OpenIDConnectConfig_To_v1alpha1_OpenIDConnectConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_kubeone_OpenIDConnect_To_v1alpha1_OpenIDConnect is an autogenerated conversion function.
func Convert_kubeone_OpenIDConnect_To_v1alpha1_OpenIDConnect(in *kubeone.OpenIDConnect, out *OpenIDConnect, s conversion.Scope) error {
	return autoConvert_kubeone_OpenIDConnect_To_v1alpha1_OpenIDConnect(in, out, s)
}

func autoConvert_v1alpha1_OpenIDConnectConfig_To_kubeone_OpenIDConnectConfig(in *OpenIDConnectConfig, out *kubeone.OpenIDConnectConfig, s conversion.Scope) error {
	out.IssuerURL = in.IssuerURL
	out.ClientID = in.ClientID
	out.UsernameClaim = in.UsernameClaim
	out.UsernamePrefix = in.UsernamePrefix
	out.GroupsClaim = in.GroupsClaim
	out.GroupsPrefix = in.GroupsPrefix
	out.RequiredClaim = in.RequiredClaim
	out.SigningAlgs = in.SigningAlgs
	out.CAFile = in.CAFile
	return nil
}

// Convert_v1alpha1_OpenIDConnectConfig_To_kubeone_OpenIDConnectConfig is an autogenerated conversion function.
func Convert_v1alpha1_OpenIDConnectConfig_To_kubeone_OpenIDConnectConfig(in *OpenIDConnectConfig, out *kubeone.OpenIDConnectConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OpenIDConnectConfig_To_kubeone_OpenIDConnectConfig(in, out, s)
}

func autoConvert_kubeone_OpenIDConnectConfig_To_v1alpha1_OpenIDConnectConfig(in *kubeone.OpenIDConnectConfig, out *OpenIDConnectConfig, s conversion.Scope) error {
	out.IssuerURL = in.IssuerURL
	out.ClientID = in.ClientID
	out.UsernameClaim = in.UsernameClaim
	out.UsernamePrefix = in.UsernamePrefix
	out.GroupsClaim = in.GroupsClaim
	out.GroupsPrefix = in.GroupsPrefix
	out.RequiredClaim = in.RequiredClaim
	out.SigningAlgs = in.SigningAlgs
	out.CAFile = in.CAFile
	return nil
}

// Convert_kubeone_OpenIDConnectConfig_To_v1alpha1_OpenIDConnectConfig is an autogenerated conversion function.
func Convert_kubeone_OpenIDConnectConfig_To_v1alpha1_OpenIDConnectConfig(in *kubeone.OpenIDConnectConfig, out *OpenIDConnectConfig, s conversion.Scope) error {
	return autoConvert_kubeone_OpenIDConnectConfig_To_v1alpha1_OpenIDConnectConfig(in, out, s)
}

func autoConvert_v1alpha1_PodSecurityPolicy_To_kubeone_PodSecurityPolicy(in *PodSecurityPolicy, out *kubeone.PodSecurityPolicy, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_v1alpha1_PodSecurityPolicy_To_kubeone_PodSecurityPolicy is an autogenerated conversion function.
func Convert_v1alpha1_PodSecurityPolicy_To_kubeone_PodSecurityPolicy(in *PodSecurityPolicy, out *kubeone.PodSecurityPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodSecurityPolicy_To_kubeone_PodSecurityPolicy(in, out, s)
}

func autoConvert_kubeone_PodSecurityPolicy_To_v1alpha1_PodSecurityPolicy(in *kubeone.PodSecurityPolicy, out *PodSecurityPolicy, s conversion.Scope) error {
	out.Enable = in.Enable
	return nil
}

// Convert_kubeone_PodSecurityPolicy_To_v1alpha1_PodSecurityPolicy is an autogenerated conversion function.
func Convert_kubeone_PodSecurityPolicy_To_v1alpha1_PodSecurityPolicy(in *kubeone.PodSecurityPolicy, out *PodSecurityPolicy, s conversion.Scope) error {
	return autoConvert_kubeone_PodSecurityPolicy_To_v1alpha1_PodSecurityPolicy(in, out, s)
}

func autoConvert_v1alpha1_ProviderSpec_To_kubeone_ProviderSpec(in *ProviderSpec, out *kubeone.ProviderSpec, s conversion.Scope) error {
	out.CloudProviderSpec = *(*json.RawMessage)(unsafe.Pointer(&in.CloudProviderSpec))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.SSHPublicKeys = *(*[]string)(unsafe.Pointer(&in.SSHPublicKeys))
	out.OperatingSystem = in.OperatingSystem
	out.OperatingSystemSpec = *(*json.RawMessage)(unsafe.Pointer(&in.OperatingSystemSpec))
	out.Network = (*kubeone.NetworkConfig)(unsafe.Pointer(in.Network))
	out.OverwriteCloudConfig = (*string)(unsafe.Pointer(in.OverwriteCloudConfig))
	return nil
}

// Convert_v1alpha1_ProviderSpec_To_kubeone_ProviderSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProviderSpec_To_kubeone_ProviderSpec(in *ProviderSpec, out *kubeone.ProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderSpec_To_kubeone_ProviderSpec(in, out, s)
}

func autoConvert_kubeone_ProviderSpec_To_v1alpha1_ProviderSpec(in *kubeone.ProviderSpec, out *ProviderSpec, s conversion.Scope) error {
	out.CloudProviderSpec = *(*json.RawMessage)(unsafe.Pointer(&in.CloudProviderSpec))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.SSHPublicKeys = *(*[]string)(unsafe.Pointer(&in.SSHPublicKeys))
	out.OperatingSystem = in.OperatingSystem
	out.OperatingSystemSpec = *(*json.RawMessage)(unsafe.Pointer(&in.OperatingSystemSpec))
	out.Network = (*NetworkConfig)(unsafe.Pointer(in.Network))
	out.OverwriteCloudConfig = (*string)(unsafe.Pointer(in.OverwriteCloudConfig))
	return nil
}

// Convert_kubeone_ProviderSpec_To_v1alpha1_ProviderSpec is an autogenerated conversion function.
func Convert_kubeone_ProviderSpec_To_v1alpha1_ProviderSpec(in *kubeone.ProviderSpec, out *ProviderSpec, s conversion.Scope) error {
	return autoConvert_kubeone_ProviderSpec_To_v1alpha1_ProviderSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxyConfig_To_kubeone_ProxyConfig(in *ProxyConfig, out *kubeone.ProxyConfig, s conversion.Scope) error {
	out.HTTP = in.HTTP
	out.HTTPS = in.HTTPS
	out.NoProxy = in.NoProxy
	return nil
}

// Convert_v1alpha1_ProxyConfig_To_kubeone_ProxyConfig is an autogenerated conversion function.
func Convert_v1alpha1_ProxyConfig_To_kubeone_ProxyConfig(in *ProxyConfig, out *kubeone.ProxyConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxyConfig_To_kubeone_ProxyConfig(in, out, s)
}

func autoConvert_kubeone_ProxyConfig_To_v1alpha1_ProxyConfig(in *kubeone.ProxyConfig, out *ProxyConfig, s conversion.Scope) error {
	out.HTTP = in.HTTP
	out.HTTPS = in.HTTPS
	out.NoProxy = in.NoProxy
	return nil
}

// Convert_kubeone_ProxyConfig_To_v1alpha1_ProxyConfig is an autogenerated conversion function.
func Convert_kubeone_ProxyConfig_To_v1alpha1_ProxyConfig(in *kubeone.ProxyConfig, out *ProxyConfig, s conversion.Scope) error {
	return autoConvert_kubeone_ProxyConfig_To_v1alpha1_ProxyConfig(in, out, s)
}

func autoConvert_v1alpha1_VersionConfig_To_kubeone_VersionConfig(in *VersionConfig, out *kubeone.VersionConfig, s conversion.Scope) error {
	out.Kubernetes = in.Kubernetes
	return nil
}

// Convert_v1alpha1_VersionConfig_To_kubeone_VersionConfig is an autogenerated conversion function.
func Convert_v1alpha1_VersionConfig_To_kubeone_VersionConfig(in *VersionConfig, out *kubeone.VersionConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_VersionConfig_To_kubeone_VersionConfig(in, out, s)
}

func autoConvert_kubeone_VersionConfig_To_v1alpha1_VersionConfig(in *kubeone.VersionConfig, out *VersionConfig, s conversion.Scope) error {
	out.Kubernetes = in.Kubernetes
	return nil
}

// Convert_kubeone_VersionConfig_To_v1alpha1_VersionConfig is an autogenerated conversion function.
func Convert_kubeone_VersionConfig_To_v1alpha1_VersionConfig(in *kubeone.VersionConfig, out *VersionConfig, s conversion.Scope) error {
	return autoConvert_kubeone_VersionConfig_To_v1alpha1_VersionConfig(in, out, s)
}

func autoConvert_v1alpha1_WorkerConfig_To_kubeone_WorkerConfig(in *WorkerConfig, out *kubeone.WorkerConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Replicas = (*int)(unsafe.Pointer(in.Replicas))
	if err := Convert_v1alpha1_ProviderSpec_To_kubeone_ProviderSpec(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_WorkerConfig_To_kubeone_WorkerConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkerConfig_To_kubeone_WorkerConfig(in *WorkerConfig, out *kubeone.WorkerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerConfig_To_kubeone_WorkerConfig(in, out, s)
}

func autoConvert_kubeone_WorkerConfig_To_v1alpha1_WorkerConfig(in *kubeone.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Replicas = (*int)(unsafe.Pointer(in.Replicas))
	if err := Convert_kubeone_ProviderSpec_To_v1alpha1_ProviderSpec(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_kubeone_WorkerConfig_To_v1alpha1_WorkerConfig is an autogenerated conversion function.
func Convert_kubeone_WorkerConfig_To_v1alpha1_WorkerConfig(in *kubeone.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	return autoConvert_kubeone_WorkerConfig_To_v1alpha1_WorkerConfig(in, out, s)
}
