---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-serving-cert
  namespace: kube-system
data:
  "cert.pem": |
{{ .Certificates.MetricsServerCert | b64enc | indent 4 }}
  "key.pem": |
{{ .Certificates.MetricsServerKey | b64enc | indent 4 }}
