---
# Source: hcloud-cloud-controller-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
---
# Source: hcloud-cloud-controller-manager/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "system:hcloud-cloud-controller-manager"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hcloud-cloud-controller-manager
    namespace: kube-system
---
# Source: hcloud-cloud-controller-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: 'hccm'
      app.kubernetes.io/name: 'hcloud-cloud-controller-manager'
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: 'hccm'
        app.kubernetes.io/name: 'hcloud-cloud-controller-manager'
      annotations:
        "kubeone.k8c.io/credentials-hash": "{{ .CredentialsCCMHash }}"
    spec:
      serviceAccountName: hcloud-cloud-controller-manager
      dnsPolicy: Default
      tolerations:
        # Allow HCCM itself to schedule on nodes that have not yet been initialized by HCCM.
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"

        # Allow HCCM to schedule on control plane nodes.
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
          operator: Exists
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
          operator: Exists

        - key: "node.kubernetes.io/not-ready"
          effect: "NoExecute"
      containers:
        - name: hcloud-cloud-controller-manager
          args:
            - "--allocate-node-cidrs=false"
            - "--allow-untagged-cloud"
            - "--cloud-provider=hcloud"
            - "--configure-cloud-routes=false"
            - "--route-reconciliation-period=30s"
            - "--webhook-secure-port=0"
            - "--leader-elect=false"
            {{- with .Params.CCM_CONCURRENT_SERVICE_SYNCS }}
            - --concurrent-service-syncs={{ . }}
            {{- end }}
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: HZ_TOKEN
                  name: kubeone-ccm-credentials
            - name: ROBOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: robot-password
                  name: hcloud
                  optional: true
            - name: ROBOT_USER
              valueFrom:
                secretKeyRef:
                  key: robot-user
                  name: hcloud
                  optional: true
            {{ with .Config.CloudProvider.Hetzner.NetworkID -}}
            - name: HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP
              value: "true"
            - name: HCLOUD_NETWORK
              value: "{{ . }}"
            {{- end }}
          image: {{ .InternalImages.Get "HetznerCCM" }}
          ports:
            - name: metrics
              containerPort: 8233
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
      priorityClassName: system-cluster-critical
