apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:hcloud-cloud-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:hcloud-cloud-controller-manager:restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:hcloud-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: hcloud-cloud-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: hccm
      app.kubernetes.io/name: hcloud-cloud-controller-manager
  template:
    metadata:
      annotations:
        kubeone.k8c.io/credentials-hash: '{{ .CredentialsCCMHash }}'
      labels:
        app.kubernetes.io/instance: hccm
        app.kubernetes.io/name: hcloud-cloud-controller-manager
    spec:
      containers:
        - args:
            - --allocate-node-cidrs=false
            - --allow-untagged-cloud
            - --cloud-provider=hcloud
            - --configure-cloud-routes=false
            - --feature-gates=CloudControllerManagerWatchBasedRoutesReconciliation=true
            - --route-reconciliation-period=30s
            - --webhook-secure-port=0
            - --leader-elect=false
            {{- with .Params.CCM_CONCURRENT_SERVICE_SYNCS }}
            - --concurrent-service-syncs={{ . }}
            {{- end }}
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: HZ_TOKEN
                  name: kubeone-ccm-credentials
            - name: ROBOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: robot-password
                  name: hcloud
                  optional: true
            - name: ROBOT_USER
              valueFrom:
                secretKeyRef:
                  key: robot-user
                  name: hcloud
                  optional: true
            {{ with .Config.CloudProvider.Hetzner.NetworkID -}}
            - name: HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP
              value: "true"
            - name: HCLOUD_NETWORK
              value: "{{ . }}"
            {{- end }}
          image: '{{ .InternalImages.Get "HetznerCCM" }}'
          name: hcloud-cloud-controller-manager
          ports:
            - containerPort: 8233
              name: metrics
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
      dnsPolicy: Default
      priorityClassName: system-cluster-critical
      serviceAccountName: hcloud-cloud-controller-manager
      tolerations:
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
