kind: Secret
apiVersion: v1
metadata:
  name: metal-cloud-config
  namespace: kube-system
data:
  cloud-sa.json: |-
    {{ EquinixMetalSecret .CredentialsCCM.METAL_AUTH_TOKEN .CredentialsCCM.METAL_PROJECT_ID | b64enc }}
