apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cilium-operator
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: cilium-operator
---

{{ if .Config.ClusterNetwork.CNI.Cilium.EnableHubble }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hubble-relay
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: hubble-relay
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: hubble-ui
{{ end }}
