---
# Source: openstack-cloud-controller-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstack-cloud-controller-manager
  namespace: kube-system
  annotations:
---
# Source: openstack-cloud-controller-manager/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openstack-cloud-controller-manager
  annotations:
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
---
# Source: openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openstack-cloud-controller-manager
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openstack-cloud-controller-manager
subjects:
- kind: ServiceAccount
  name: openstack-cloud-controller-manager
  namespace: "kube-system"
---
# Source: openstack-cloud-controller-manager/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openstack-cloud-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: openstack-cloud-controller-manager
    helm.sh/chart: openstack-cloud-controller-manager-2.27.1
    app.kubernetes.io/instance: openstack-ccm
    app.kubernetes.io/version: "v1.27.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  selector:
    matchLabels:
      component: controllermanager
      app: openstack-cloud-controller-manager
      release: openstack-ccm
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        "kubeone.k8c.io/cabundle-hash": "{{ .Config.CABundle | sha256sum }}"
        "kubeone.k8c.io/cloudconfig-hash": "{{ .Config.CloudProvider.CloudConfig | sha256sum }}"
      labels:
        component: controllermanager
        app: openstack-cloud-controller-manager
        k8s-app: openstack-cloud-controller-manager
        release: openstack-ccm
        chart: openstack-cloud-controller-manager-2.27.1
        heritage: Helm
      annotations:
    spec:
      securityContext:
        runAsUser: 1001
      tolerations:
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      serviceAccountName: openstack-cloud-controller-manager
      containers:
        - name: openstack-cloud-controller-manager
          image: {{ .InternalImages.Get "OpenstackCCM" }}
          args:
            - /bin/openstack-cloud-controller-manager
            - --v=1
            - --cloud-config=$(CLOUD_CONFIG)
            - --cluster-name=$(CLUSTER_NAME)
            - --cloud-provider=openstack
            - --controllers=cloud-node,cloud-node-lifecycle,route,service
            - --bind-address=127.0.0.1
          volumeMounts:
            - mountPath: /etc/config
              name: cloud-config-volume
              readOnly: true
            - mountPath: /etc/kubernetes/pki
              name: k8s-certs
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certs
              readOnly: true
            - mountPath: /etc/pki
              name: pki-certs
              readOnly: true
            - mountPath: /usr/share/ca-certificates
              name: usr-ca-certs
              readOnly: true
{{ if .Config.CABundle }}
{{ caBundleVolumeMount | indent 12 }}
{{ end }}
          env:
            - name: CLOUD_CONFIG
              value: /etc/config/cloud-config
            - name: CLUSTER_NAME
              value: {{ default "kubernetes" .CCMClusterName }}
{{ if .Config.CABundle }}
{{ caBundleEnvVar | indent 12 }}
{{ end }}
      hostNetwork: true
      priorityClassName: "system-cluster-critical"
      volumes:
      - name: cloud-config-volume
        secret:
          secretName: cloud-config

      - hostPath:
          path: /etc/kubernetes/pki
          type: DirectoryOrCreate
        name: k8s-certs
      - hostPath:
          path: /etc/ssl/certs
          type: DirectoryOrCreate
        name: ca-certs
      - hostPath:
          path: /etc/pki
          type: DirectoryOrCreate
        name: pki-certs
      - hostPath:
          path: /usr/share/ca-certificates
          type: DirectoryOrCreate
        name: usr-ca-certs
{{ if .Config.CABundle }}
{{ caBundleVolume | indent 6 }}
{{ end }}
