apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system
data:
  calico_backend: vxlan
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
            "type": "calico-ipam",
            {{ if and .Config.ClusterNetwork.HasIPv4 .Config.ClusterNetwork.HasIPv6 }}
            "ranges": [
              [{"subnet": "usePodCidr"}],
              [{"subnet": "usePodCidrIPv6"}]
            ]
            {{ else }}
            {{ if .Config.ClusterNetwork.HasIPv6 }}
            "subnet": "usePodCidrIPv6"
            {{ else }}
            "subnet": "usePodCidr"
            {{ end }}
            {{ end }}
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {
            "portMappings": true
          }
        },
        {
          "type": "bandwidth",
          "capabilities": {
            "bandwidth": true
          }
        }
      ]
    }
  typha_service_name: none
  veth_mtu: "{{ default 0 .Params.MTU }}"

  {{ if .Config.ClusterNetwork.HasIPv4 }}
  # The default IPv4 pool to create on startup if none exists. Pod IPs will be
  # chosen from this range. Changing this value after installation will have
  # no effect. This should fall within `--cluster-cidr`.
  CALICO_IPV4POOL_CIDR: "{{ .Config.ClusterNetwork.PodSubnet }}"
  {{ end }}

  {{ if .Config.ClusterNetwork.HasIPv6 }}
  FELIX_IPV6SUPPORT: "true"
  IP6: "autodetect"
  CALICO_IPV6POOL_CIDR: "{{ .Config.ClusterNetwork.PodSubnetIPv6 }}"
  {{ else }}
  # Disable IPv6 on Kubernetes.
  FELIX_IPV6SUPPORT: "false"
  {{ end }}
