apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-provider-equinix-metal
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-provider-equinix-metal
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - metallb.io
    resources:
      - ipaddresspools
      - bgppeers
      - bgpadvertisements
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-provider-equinix-metal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-provider-equinix-metal
subjects:
  - kind: ServiceAccount
    name: cloud-provider-equinix-metal
    namespace: kube-system
---
apiVersion: v1
data:
  cloud-sa.json: '{{ EquinixMetalSecret .CredentialsCCM.METAL_AUTH_TOKEN .CredentialsCCM.METAL_PROJECT_ID | b64enc }}'
kind: Secret
metadata:
  name: metal-cloud-config
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cloud-provider-equinix-metal
  name: cloud-provider-equinix-metal
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cloud-provider-equinix-metal
  template:
    metadata:
      annotations:
        kubeone.k8c.io/credentials-hash: '{{ .CredentialsCCMHash }}'
      labels:
        app: cloud-provider-equinix-metal
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - master
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      containers:
        - command:
            - ./cloud-provider-equinix-metal
            - --cloud-provider=equinixmetal
            - --leader-elect=true
            - --authentication-skip-lookup=true
            - --cloud-config=/etc/cloud-sa/cloud-sa.json
            - --concurrent-service-syncs={{ default 0 .Params.CCM_CONCURRENT_SERVICE_SYNCS }}
          image: '{{ .InternalImages.Get "EquinixMetalCCM" }}'
          imagePullPolicy: Always
          name: cloud-provider-equinix-metal
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - mountPath: /etc/cloud-sa
              name: cloud-sa-volume
              readOnly: true
      dnsPolicy: Default
      hostNetwork: true
      priorityClassName: system-cluster-critical
      serviceAccountName: cloud-provider-equinix-metal
      tolerations:
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
      volumes:
        - name: cloud-sa-volume
          secret:
            secretName: metal-cloud-config
