apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: azure-cloud-controller-manager
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: azure-cloud-controller-manager
