name: govulncheck
on:
  pull_request:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
