name: mirror-images

on:
  push:
    tags:
      - "v1.*"
  workflow_dispatch: {}

# Prevent concurrent mirroring
concurrency:
  group: mirror-images
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions: {}

jobs:
  mirror-images:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write # to write the mirrored images to GHCR
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: build kubeone
        run: |
          make install
      - name: login to GHCR
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: mirror kubeone images
        run: |
          kubeone mirror-images ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
