name: release

on:
  push:
    tags:
      - "v1.*"

# Prevent concurrent releases
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  gorelease:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write # Needed for GoReleaser to create releases and upload SBOMs
      id-token: write # Needed for keyless signing via Sigstore
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0

      - name: fetch default stable for Kubernetes
        run: |
          echo "DEFAULT_STABLE=$(curl -SsL "$(cat hack/stable-kubernetes-url.txt)")" >> "$GITHUB_ENV"

      - name: GoReleaser run
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --parallelism 1 --fail-fast
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
